### PR TITLE
Multi browser

### LINKED ISSUE #26: Allow users to play on different computers

### PR DESCRIPTION
**Pull request by lena-pl**
- [x] A player should be able to create a game and become its participant
- [x] Once a game is created, the player can invite a friend to play with them
- [x] Each player should have unique identifiers for security
- [x] The players should be stored in a session to differentiate between them
- [x] The game shouldn't start until both players are connected
- [x] The window should not redirect to show opponent's cards
- [x] The player shouldn't be allowed to make a move if it's not their turn
- [x] The window should refresh automatically once a move has been made
- [x] The form submit should be AJAX also
- [x] The user id/token should not be visible to the user via URL

Will fix #26

### CODE REVIEW

**Comment by lena-pl** [comment]
Polling-powered auto-refresh if functional

**Comment by shadrx** [comment]
:sparkles:

**Comment by lena-pl** [comment]
- All functionality complete
- Tests need to be modified

**Comment by lena-pl** [comment]
Polling on this branch also fixes #28

**Comment by lena-pl** [comment]
Back to 100% coverage

**Pull request merged**
